
name: Docker publish

on:
  push:
    branches:
      - main
  #
  # Run monthly on the 10th at 06:42
  #
  schedule:
    - cron: '42 6 10 * *'

  workflow_dispatch:

jobs:

  k3s:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: docker.stackable.tech
          username: github
          password: ${{ secrets.NEXUS_PASSWORD }}

      - uses: docker/build-push-action@v2.4.0
        with:
          file: k3s/Dockerfile
          tags: docker.stackable.tech/k3s:latest
          push: true

  debian:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: docker.stackable.tech
          username: github
          password: ${{ secrets.NEXUS_PASSWORD }}

      - uses: docker/build-push-action@v2.4.0
        with:
          file: debian/Dockerfile
          tags: docker.stackable.tech/debian-devel-base:latest
          push: true

  centos:
    strategy:
      matrix:
        os_version: [ 7, 8 ]

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: docker.stackable.tech
          username: github
          password: ${{ secrets.NEXUS_PASSWORD }}

      - uses: docker/build-push-action@v2.4.0
        with:
          file: centos/Dockerfile
          build-args: OS_VERSION=${{ matrix.os_version }}
          tags: docker.stackable.tech/centos${{ matrix.os_version }}-devel-base:latest
          push: true
